### ISSUE TITLE
Bug: Command palette does not open

### ISSUE THREAD

**Issue by nosas** [kjk/edna#64]
**Describe the bug**
Pressing `CTRL+SHIFT+P`, or `CTRL+P` then typing `>`, does not open command palette. 

**To Reproduce**
1. Go to any note
2. Either press `CTRL+SHIFT+P`, or `CTRL+P` then type `>`
3. No command palette

**Expected behavior**
Command palette should open up

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Browser: Arc Browser (Version 1.49.1 (51495))

**Additional context**
Relevant console traceback (is there a better way to provide this information?):

```
initialSelection: 0 n: 3
index-DNIA00ZX.js:2900 select: 0 nItems: 3
index-DNIA00ZX.js:2937 Switch to command palette
index-DNIA00ZX.js:2943 openCommandPalette
index-DNIA00ZX.js:2943 Uncaught ReferenceError: state is not defined
    at to (index-DNIA00ZX.js:2943:3749)
    at Sr (index-DNIA00ZX.js:2943:3631)
    at xe (index-DNIA00ZX.js:2943:5801)
    at xe (index-DNIA00ZX.js:2943:5756)
    at ao (index-DNIA00ZX.js:2943:5896)
    at ur (index-DNIA00ZX.js:2943:6029)
    at Object.Gt [as switchToCommandPalette] (index-DNIA00ZX.js:2937:941)
    at index-DNIA00ZX.js:2900:44177
    at execute_reaction_fn (index-DNIA00ZX.js:3:11992)
    at update_derived (index-DNIA00ZX.js:3:9734)
```

**Comment by kjk** [comment]
should be fixed if you refresh
